-- =========================================================================
-- BUSINESS QUERIES (BÁO CÁO, THỐNG KÊ, TRA CỨU)
-- =========================================================================

--Tra cứu thông tin phim theo tên phim, thể loại hoặc thời lượng
SELECT MAPHIM, TENPHIM, THELOAI, THOILUONG 
FROM PHIM
WHERE TENPHIM LIKE N'%Avengers%' 
   OR THELOAI LIKE N'%Hành động%' 
   OR THOILUONG BETWEEN 100 AND 150;

--Liệt kê danh sách khách hàng tham gia một suất chiếu cụ thể
SELECT DISTINCT KH.MAKH, KH.HOTEN, KH.SDT, KH.EMAIL
FROM KHACH_HANG KH
JOIN HOA_DON HD ON KH.MAKH = HD.MAKH
JOIN VE V ON HD.MAHOADON = V.MAHOADON
WHERE V.MASUATCHIEU = 'SC001';

--Thống kê số lượng suất chiếu của từng phim
SELECT P.MAPHIM, P.TENPHIM, COUNT(SC.MASUATCHIEU) AS SOSUATCHIEU
FROM PHIM P
JOIN SUAT_CHIEU SC ON P.MAPHIM = SC.MAPHIM
GROUP BY P.MAPHIM, P.TENPHIM;

--Tìm các suất chiếu có số lượng vé bán nhiều nhất hoặc ít nhất
--Suất chiếu có số lượng vé bán nhiều nhất:
SELECT TOP 1 MASUATCHIEU, COUNT(MAVE) AS VE_BAN_DUOC
FROM VE
GROUP BY MASUATCHIEU
ORDER BY COUNT(MAVE) DESC;

--Suất chiếu có số lượng vé bán ít nhất:
SELECT TOP 1 MASUATCHIEU, COUNT(MAVE) AS VE_BAN_DUOC
FROM VE
GROUP BY MASUATCHIEU
ORDER BY COUNT(MAVE) ASC;

--Tìm các phim được xem nhiều nhất trong một khoảng thời gian
SELECT TOP 3 P.MAPHIM, P.TENPHIM, COUNT(V.MAVE) AS TONG_SO_VE
FROM PHIM P
JOIN SUAT_CHIEU SC ON P.MAPHIM = SC.MAPHIM
JOIN VE V ON SC.MASUATCHIEU = V.MASUATCHIEU
JOIN HOA_DON HD ON V.MAHOADON = HD.MAHOADON
WHERE HD.NGAYMUA BETWEEN '2026-07-19' AND '2026-07-25'
GROUP BY P.MAPHIM, P.TENPHIM
ORDER BY TONG_SO_VE DESC;

--Liệt kê các phim không có vé bán trong tháng
SELECT MAPHIM, TENPHIM, THELOAI
FROM PHIM
WHERE MAPHIM NOT IN (
    SELECT DISTINCT SC.MAPHIM
    FROM SUAT_CHIEU SC
    JOIN VE V ON SC.MASUATCHIEU = V.MASUATCHIEU
    JOIN HOA_DON HD ON V.MAHOADON = HD.MAHOADON
    WHERE MONTH(HD.NGAYMUA) = 7 AND YEAR(HD.NGAYMUA) = 2026
);

--Thống kê số lượng khách hàng mua vé theo từng khoảng thời gian
SELECT HD.NGAYMUA AS NGAY_GIAO_DICH, COUNT(DISTINCT HD.MAKH) AS SO_LUONG_KH_MUA
FROM HOA_DON HD
GROUP BY HD.NGAYMUA;

--Lập báo cáo tình hình kinh doanh của rạp theo từng tháng hoặc từng năm
SELECT MONTH(HD.NGAYMUA) AS THANG, YEAR(HD.NGAYMUA) AS NAM, COUNT(V.MAVE) AS TONG_VE_BAN, SUM(V.GIAVEMUA) AS TONG_DOANH_THU
FROM HOA_DON HD
JOIN VE V ON HD.MAHOADON = V.MAHOADON
GROUP BY MONTH(HD.NGAYMUA), YEAR(HD.NGAYMUA);

--Lập báo cáo tổng quan toàn cục của hệ thống rạp
SELECT P.TENPHIM AS [TÊN PHIM], COUNT(DISTINCT SC.MASUATCHIEU) AS [SỐ SUẤT CHIẾU], COUNT(DISTINCT HD.MAKH) AS [SỐ KHÁCH HÀNG], COUNT(V.MAVE) AS [TỔNG VÉ BÁN], SUM(V.GIAVEMUA) AS [DOANH THU THU VỀ]
FROM PHIM P
JOIN SUAT_CHIEU SC ON P.MAPHIM = SC.MAPHIM
JOIN VE V ON SC.MASUATCHIEU = V.MASUATCHIEU
JOIN HOA_DON HD ON V.MAHOADON = HD.MAHOADON
GROUP BY P.MAPHIM, P.TENPHIM;

